### ISSUE TITLE
[DEV] Cleaning up pokemon & items running every 10 seconds

### ISSUE THREAD

**Issue by Drambuie** [PokemonGoF/PokemonGo-Bot#1170]
### Expected Behavior

Using the following config, I would expect the bot to perform periodic checks on the bag and pokemon an perform cleanup actions 

We need to an option to be able to adjust the period of time between pokemon and bag checks

    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "1": { "keep" : 200 },
      "2": { "keep" : 100 },
      "3": { "keep" : 100 },
      "101": { "keep" : 10 },
      "102": { "keep" : 30 },
      "103": { "keep" : 30 },
      "201": { "keep" : 30 },
      "701": { "keep" : 100 }
    },
    "evolve_all": "NONE",
    "evolve_speed": 20,
    "cp_min": 300,
    "use_lucky_egg": false,
    "evolve_captured": false,
    "catch": {
      "any": {"always_catch": true}
    },
    "release": {
      "any": {"release_below_cp": 350, "release_below_iv": 0.8, "logic": "and"}
    }
}

### Actual Behavior

What appears to be happenins is every 10 seconds it is stopping the bot from walking and performing "Cleaning up Pokemon Bag using the release config"  & "Starting to recycle items..." which is causing the bot to take 10 seconds to walk a metre

[======                                  ] 15%[11:00:42] Cleaning up Pokemon Bag using the release config
[11:00:42] Pokemon Bag has been cleaned up!
[11:00:42] Starting to recycle items...
[11:00:45] Finished.
[11:00:45] Found fort 8ddf880cb75f4e05979d07368dff1cb5.16 at distance 0.23km
[11:00:45] Need to move closer to Pokestop
[========                                ] 22%[11:00:51] Cleaning up Pokemon Bag using the release config
[11:00:52] Pokemon Bag has been cleaned up!
[11:00:52] Starting to recycle items...
[11:00:54] Finished.
[11:00:54] Found fort 8ddf880cb75f4e05979d07368dff1cb5.16 at distance 0.22km
[11:00:54] Need to move closer to Pokestop
[==========                              ] 26%[11:01:00] Cleaning up Pokemon Bag using the release config
[11:01:01] Pokemon Bag has been cleaned up!
[11:01:01] Starting to recycle items...
[11:01:03] Finished.
[11:01:03] Found fort 8ddf880cb75f4e05979d07368dff1cb5.16 at distance 0.22km
[11:01:03] Need to move closer to Pokestop
[===========                             ] 29%[11:01:09] Cleaning up Pokemon Bag using the release config
[11:01:10] Pokemon Bag has been cleaned up!
[11:01:10] Starting to recycle items...
[11:01:12] Finished.
[11:01:12] Found fort 8ddf880cb75f4e05979d07368dff1cb5.16 at distance 0.21km
[11:01:12] Need to move closer to Pokestop
[=============                           ] 33%[11:01:19] Cleaning up Pokemon Bag using the release config
[11:01:19] Pokemon Bag has been cleaned up!
[11:01:19] Starting to recycle items...
[11:01:22] Finished.
[11:01:22] Found fort 8ddf880cb75f4e05979d07368dff1cb5.16 at distance 0.20km
[11:01:22] Need to move closer to Pokestop
[===============                         ] 39%[11:01:27] Cleaning up Pokemon Bag using the release config
[11:01:28] Pokemon Bag has been cleaned up!
[11:01:28] Starting to recycle items...
[11:01:30] Finished.
[11:01:30] Found fort 8ddf880cb75f4e05979d07368dff1cb5.16 at distance 0.19km
[11:01:30] Need to move closer to Pokestop
[================                        ] 42%[11:01:36] Cleaning up Pokemon Bag using the release config
[11:01:36] Pokemon Bag has been cleaned up!
[11:01:36] Starting to recycle items...
[11:01:39] Finished.
[11:01:39] Found fort 8ddf880cb75f4e05979d07368dff1cb5.16 at distance 0.18km
[11:01:39] Need to move closer to Pokestop
[==================                      ] 46%[11:01:45] Cleaning up Pokemon Bag using the release config
[11:01:45] Pokemon Bag has been cleaned up!
[11:01:45] Starting to recycle items...
[11:01:48] Finished.
[11:01:48] Found fort 8ddf880cb75f4e05979d07368dff1cb5.16 at distance 0.17km
[11:01:48] Need to move closer to Pokestop
[====================                    ] 50%[11:01:54] Cleaning up Pokemon Bag using the release config
[11:01:54] Pokemon Bag has been cleaned up!
[11:01:54] Starting to recycle items...
[11:01:57] Finished.
[11:01:57] Something rustles nearby!
[11:01:58] A Wild Staryu appeared! [CP 111] [Potential 0.53]
[11:01:58] IV [Stamina/Attack/Defense] = [6/9/9]
[11:02:02] Using Pokeball (chance: 68.91%)... (135 left!)
[11:02:03] Captured Staryu! [CP 111] [6/9/9]
[11:02:08] Found fort 8ddf880cb75f4e05979d07368dff1cb5.16 at distance 0.17km
[11:02:08] Need to move closer to Pokestop
[=====================                   ] 54%[11:02:14] Cleaning up Pokemon Bag using the release config
[11:02:15] Exchanging Staryu [CP 111] [Potential 0.53]
[11:02:18] Pokemon Bag has been cleaned up!
[11:02:18] Starting to recycle items...
[11:02:21] Finished.
[11:02:21] Something rustles nearby!
[11:02:21] A Wild Rattata appeared! [CP 23] [Potential 0.67]
[11:02:21] IV [Stamina/Attack/Defense] = [8/11/11]
[11:02:25] Using Pokeball (chance: 100.00%)... (134 left!)
[11:02:26] Captured Rattata! [CP 23] [8/11/11]
[11:02:31] Found fort 8ddf880cb75f4e05979d07368dff1cb5.16 at distance 0.16km
[11:02:31] Need to move closer to Pokestop
[=======================                 ] 58%[11:02:37] Cleaning up Pokemon Bag using the release config
[11:02:37] Exchanging Rattata [CP 23] [Potential 0.67]
[11:02:40] Pokemon Bag has been cleaned up!
[11:02:40] Starting to recycle items...
[11:02:43] Finished.
[11:02:43] Found fort 8ddf880cb75f4e05979d07368dff1cb5.16 at distance 0.15km
[11:02:43] Need to move closer to Pokestop
[========================                ] 61%[11:02:48] Cleaning up Pokemon Bag using the release config
[11:02:49] Pokemon Bag has been cleaned up!
[11:02:49] Starting to recycle items...
[11:02:51] Finished.
[11:02:51] Found fort 8ddf880cb75f4e05979d07368dff1cb5.16 at distance 0.15km
[11:02:51] Need to move closer to Pokestop
[=========================               ] 64%[11:02:57] Cleaning up Pokemon Bag using the release config
[11:02:58] Pokemon Bag has been cleaned up!
[11:02:58] Starting to recycle items...
[11:03:01] Finished.

### Steps to Reproduce

Run the above config

### Other Information
OS: Ubuntu
Git Commit:e062e548268c37bf8b02946d88ae6fcd0adb4ed6

**Comment by TheSavior** [comment]
Fixed a few minutes ago

**Comment by Drambuie** [comment]
@TheSavior Cleaning up Pokemon bit appears resolved,

However am still seeing Starting to recycle items... every 10 seconds

**Comment by Cromir** [comment]
@TheSavior confirmed issue.
![screen shot 2016-07-27 at 12 16 03](https://cloud.githubusercontent.com/assets/3354358/17172148/ff3ee9bc-53f3-11e6-982c-0573101b26a4.png)

**Comment by TheSavior** [comment]
Ah, right. Looks like @surfaace is taking care of it here: https://github.com/PokemonGoF/PokemonGo-Bot/pull/1171

**Comment by BoGnY** [comment]
I confim the issue with the latest dev branch...

> [12:17:09] Starting PokemonGo Bot....
[12:17:09] Scanning area for objects....
[12:17:09] Walking from (45.6668893, 12.2430437) to [45.6668893, 12.2430437] 0.00km
[12:17:11] Starting to recycle items...
[12:17:16] Finished.
[12:17:16] Something rustles nearby!
[12:17:17] A Wild Doduo appeared! [CP 193] [Potential 0.49]
[12:17:17] IV [Stamina/Attack/Defense] = [8/13/1]
[12:17:20] Using Pokeball (chance: 50.05%)... (87 left!)
[12:17:21] Captured Doduo! [CP 193] [8/13/1]
[12:17:26] Found fort d73f0df9e32d4824be76e678d99ab1d0.16 at distance 0.02km
[12:17:26] Need to move closer to Pokestop
[12:17:30] Scanning area for objects....
[12:17:30] Walking from (45.66686601588999, 12.243045108533014) to [45.668689300000004, 12.2430437] 0.20km
[12:17:34] Starting to recycle items...
[12:17:39] Finished.

After a few minutes, bot crash..
And, on pokestop, the bot don't collect any items..

**Comment by Drambuie** [comment]
will retest after #1171 is commited

**Comment by Drambuie** [comment]
Seems better after #1171 

Thou i do think that the walking speed is still to slow,

Still showing 10 seconds to walk a metre

**Comment by TheSavior** [comment]
This ticket has been resolved. The walking speed is a different issue and is currently being worked on by @douglascamata
