### ISSUE TITLE
How to make it keep 1 best pokemon but 3 best eevee's

### ISSUE THREAD

**Issue by Parth6182** [PokemonGoF/PokemonGo-Bot#2071]
How to make the bot release all pokemon except one of each type but also keep 3 of the best eevees

**Comment by beranPro** [comment]
See the comments in the config.json.example

**Comment by Parth6182** [comment]
"release": {
      "any": {"keep_best_cp": 1}
       Eevee": {"keep_best_cp": 3},
    },

Is not working

**Comment by SvenPe** [comment]
It should be working fine if you add the " in front of Eevee

like this: 

"release": {
"any": {"keep_best_cp": 1}
"Eevee": {"keep_best_cp": 3},
},

**Comment by Parth6182** [comment]
My bot doesn't start if i use this 

"release": {
      "any": {"keep_best_cp": 1},
      "Eevee": {"keep_best_cp": 3},
},

**Comment by SvenPe** [comment]
Missed another comma when correcting your syntax. This should work now

"release": {
"any": {"keep_best_cp": 1},
"Eevee": {"keep_best_cp": 3},
},

**Comment by Parth6182** [comment]
^ I've put the comma in my previous comment but it still doesn't let my bot start

**Comment by Parth6182** [comment]
Thanks for the help guys :D 

This worked in the end 

"release": {
"any": {"keep_best_cp": 1},
"Eevee": {"keep_best_cp": 3}
},

**Comment by Parth6182** [comment]
^ The line with the single pokemon should not have a comma at the end
