### ISSUE TITLE
[DEV] Bot moves away from fort, instead of moving towards it.

### ISSUE THREAD

**Issue by LeonJansen** [PokemonGoF/PokemonGo-Bot#2197]
### Expected Behavior
Walking towards fort

### Actual Behavior
Moving away from fort

### Steps to Reproduce
DEV Branch, starting bot with default config.

### Other Information
OS: Windows 10
Git Commit: 10589b0efdc2e31b3c478fd16df8c0f753be061b
Python Version: Python 2.7.10

![bug](https://cloud.githubusercontent.com/assets/4737467/17288362/04c4c084-57d5-11e6-8bf9-70b0d08c09c2.PNG)

**Comment by tstumm** [comment]
Please post your config.json - don't forget to anonymize it.
Most probably you have misconfigured the bot. Make sure FollowSpiral is the last job in your task list.

**Comment by LeonJansen** [comment]
This is my config:

`{
    "auth_service": "google",
    "username": "USERNAME",
    "password": "PASSWORD",
    "location": "Location",
    "gmapkey": "GMAPKEY",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolveAll",
        "config": {
          "evolve_speed": 20,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems"
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort"
      },
      {
        "type": "FollowSpiral"
      }
    ],
    "max_steps": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "1": { "keep" : 50 },
      "2": { "keep" : 50 },
      "3": { "keep" : 50 },
      "101": { "keep" : 10 },
      "102": { "keep" : 25 },
      "103": { "keep" : 25 },
      "201": { "keep" : 25 },
      "701": { "keep" : 100 }
    },
    "evolve_all": "Pidgey,Weedle",
    "evolve_cp_min": 300,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or" },

      "// Pokemons with example": { "always_catch": true },
      "// Gets filtered with release parameters": {},

      "// Legendary pokemons (Goes under S-Tier)": {},
      "Lapras": { "always_catch": true },
      "Moltres": { "always_catch": true },
      "Zapdos": { "always_catch": true },
      "Articuno": { "always_catch": true },

      "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
      "Mewtwo": { "always_catch": true },
      "Dragonite": { "always_catch": true },
      "Snorlax": { "always_catch": true },
      "// Mew evolves to Mewtwo": {},
      "Mew": { "always_catch": true },
      "Arcanine": { "always_catch": true },
      "Vaporeon": { "always_catch": true },
      "Gyarados": { "always_catch": true },
      "Exeggutor": { "always_catch": true },
      "Muk": { "always_catch": true },
      "Weezing": { "always_catch": true },
      "Flareon": { "always_catch": true },

      "// Growlithe evolves to Arcanine": {},
      "Growlithe": { "always_catch": true },
      "// Dragonair evolves to Dragonite": {},
      "Dragonair": { "always_catch": true },
      "// Grimer evolves to Muk": {},
      "Grimer": { "always_catch": true },

      "// Magikarp evolves to Gyarados": {},
      "Magikarp": { "always_catch": true },
      "// Exeggcute evolves to Exeggutor": {},
      "Exeggcute": { "always_catch": true },
      "// Eevee evolves to many versions, like Vaporeon, Flareon": {},
      "Eevee": { "always_catch": true },

      "// A-Tier pokemons": {},
      "Slowbro": { "always_catch": true },
      "Victreebel": { "always_catch": true },
      "Machamp": { "always_catch": true },
      "Poliwrath": { "always_catch": true },
      "Clefable": { "always_catch": true },
      "Nidoking": { "always_catch": true },
      "Venusaur": { "always_catch": true },
      "Charizard": { "always_catch": true },
      "Golduck": { "always_catch": true },
      "Nidoqueen": { "always_catch": true },
      "Vileplume": { "always_catch": true },
      "Blastoise": { "always_catch": true },
      "Omastar":  { "always_catch": true },
      "Aerodactyl": { "always_catch": true },
      "Golem": { "always_catch": true },
      "Wigglytuff": { "always_catch": true },
      "Dewgong": { "always_catch": true },
      "Ninetales": { "always_catch": true },
      "Magmar": { "always_catch": true },
      "Kabutops": { "always_catch": true },
      "Electabuzz": { "always_catch": true },
      "Starmie": { "always_catch": true },
      "Jolteon": { "always_catch": true },
      "Rapidash": { "always_catch": true },
      "Pinsir": { "always_catch": true },
      "Scyther": { "always_catch": true },
      "Tentacruel": { "always_catch": true },
      "Gengar": { "always_catch": true },
      "Hypno": { "always_catch": true },
      "Pidgeot": { "always_catch": true },
      "Rhydon": { "always_catch": true },
      "Seaking": { "always_catch": true },
      "Kangaskhan": { "always_catch": true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or" },

      "// Legendary pokemons (Goes under S-Tier)": {},
      "Lapras": { "release_below_cp": 1041, "release_below_iv": 0.8, "logic": "and" },
      "Moltres": { "release_below_cp": 1132, "release_below_iv": 0.8, "logic": "and" },
      "Zapdos": { "release_below_cp": 1087, "release_below_iv": 0.8, "logic": "and" },
      "Articuno": { "release_below_cp": 1039, "release_below_iv": 0.8, "logic": "and" },

      "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
      "Mewtwo": { "release_below_cp": 1447, "release_below_iv": 0.8, "logic": "and"},
      "Dragonite": { "release_below_cp": 1221, "release_below_iv": 0.8, "logic": "and" },
      "Snorlax": { "release_below_cp": 1087, "release_below_iv": 0.8, "logic": "and" },
      "// Mew evolves to Mewtwo": {},
      "Mew": { "release_below_cp": 1152, "release_below_iv": 0.8, "logic": "and" },
      "Arcanine": { "release_below_cp": 1041, "release_below_iv": 0.8, "logic": "and" },
      "Vaporeon": { "release_below_cp": 984, "release_below_iv": 0.8, "logic": "and" },
      "Gyarados": { "release_below_cp": 938, "release_below_iv": 0.8, "logic": "and" },
      "Exeggutor": { "release_below_cp": 1032, "release_below_iv": 0.8, "logic": "and" },
      "Muk": { "release_below_cp": 909, "release_below_iv": 0.8, "logic": "and" },
      "Weezing": { "release_below_cp": 784, "release_below_iv": 0.8, "logic": "and" },
      "Flareon": { "release_below_cp": 924, "release_below_iv": 0.8, "logic": "and" },

      "// Growlithe evolves to Arcanine": {},
      "Growlithe": { "release_below_cp": 465, "release_below_iv": 0.8, "logic": "and" },
      "// Dragonair evolves to Dragonite": {},
      "Dragonair": { "release_below_cp": 609, "release_below_iv": 0.8, "logic": "and" },
      "// Grimer evolves to Muk": {},
      "Grimer": { "release_below_cp": 448, "release_below_iv": 0.8, "logic": "and" },
      "// Magikarp evolves to Gyarados": {},
      "Magikarp": { "release_below_cp": 91, "release_below_iv": 0.8, "logic": "and" },
      "// Exeggcute evolves to Exeggutor": {},
      "Exeggcute": { "release_below_cp": 384, "release_below_iv": 0.8, "logic": "and" },
      "// Eevee evolves to many versions, like Vaporeon, Flareon": {},
      "Eevee": { "release_below_cp": 376, "release_below_iv": 0.8, "logic": "and" },

      "// A-Tier pokemons": {},
      "Slowbro": { "release_below_cp": 907, "release_below_iv": 0.8, "logic": "and" },
      "Victreebel": { "release_below_cp": 883, "release_below_iv": 0.8, "logic": "and" },
      "Machamp": { "release_below_cp": 907, "release_below_iv": 0.8, "logic": "and" },
      "Poliwrath": { "release_below_cp": 876, "release_below_iv": 0.8, "logic": "and" },
      "Clefable": { "release_below_cp": 837, "release_below_iv": 0.8, "logic": "and" },
      "Nidoking": { "release_below_cp": 864, "release_below_iv": 0.8, "logic": "and" },
      "Venusaur": { "release_below_cp": 902, "release_below_iv": 0.8, "logic": "and" },
      "Charizard": { "release_below_cp": 909, "release_below_iv": 0.8, "logic": "and" },
      "Golduck": { "release_below_cp": 832, "release_below_iv": 0.8, "logic": "and" },
      "Nidoqueen": { "release_below_cp": 868, "release_below_iv": 0.8, "logic": "and" },
      "Vileplume": { "release_below_cp": 871, "release_below_iv": 0.8, "logic": "and" },
      "Blastoise": { "release_below_cp": 888, "release_below_iv": 0.8, "logic": "and" },
      "Omastar":  { "release_below_cp": 780, "release_below_iv": 0.8, "logic": "and" },
      "Aerodactyl": { "release_below_cp": 756, "release_below_iv": 0.8, "logic": "and" },
      "Golem": { "release_below_cp": 804, "release_below_iv": 0.8, "logic": "and" },
      "Wigglytuff": { "release_below_cp": 760, "release_below_iv": 0.8, "logic": "and" },
      "Dewgong": { "release_below_cp": 748, "release_below_iv": 0.8, "logic": "and" },
      "Ninetales": { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
      "Magmar": { "release_below_cp": 792, "release_below_iv": 0.8, "logic": "and" },
      "Kabutops": { "release_below_cp": 744, "release_below_iv": 0.8, "logic": "and" },
      "Electabuzz": { "release_below_cp": 739, "release_below_iv": 0.8, "logic": "and" },
      "Starmie": { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
      "Jolteon": { "release_below_cp": 746, "release_below_iv": 0.8, "logic": "and" },
      "Rapidash": { "release_below_cp": 768, "release_below_iv": 0.8, "logic": "and" },
      "Pinsir": { "release_below_cp": 741, "release_below_iv": 0.8, "logic": "and" },
      "Scyther": { "release_below_cp": 724, "release_below_iv": 0.8, "logic": "and" },
      "Tentacruel": { "release_below_cp": 775, "release_below_iv": 0.8, "logic": "and" },
      "Gengar": { "release_below_cp": 724, "release_below_iv": 0.8, "logic": "and" },
      "Hypno": { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
      "Pidgeot": { "release_below_cp": 729, "release_below_iv": 0.8, "logic": "and" },
      "Rhydon": { "release_below_cp": 782, "release_below_iv": 0.8, "logic": "and" },
      "Seaking": { "release_below_cp": 712, "release_below_iv": 0.8, "logic": "and" },
      "Kangaskhan": { "release_below_cp": 712, "release_below_iv": 0.8, "logic": "and" },

      "// Koffing evolves to Weezing (A-Tier)": {},
      "Koffing": { "release_below_cp": 403, "release_below_iv": 0.8, "logic": "and" },

      "// Below is B-tier and lower pokemons": {},
      "Caterpie": { "release_below_cp": 156, "release_below_iv": 0.8, "logic": "and" },
      "Weedle": { "release_below_cp": 156, "release_below_iv": 0.8, "logic": "and" },
      "Diglett": { "release_below_cp": 158, "release_below_iv": 0.8, "logic": "and" },
      "Metapod": { "release_below_cp": 168, "release_below_iv": 0.8, "logic": "and" },
      "Kakuna": { "release_below_cp": 170, "release_below_iv": 0.8, "logic": "and" },
      "Rattata": { "release_below_cp": 204, "release_below_iv": 0.8, "logic": "and" },
      "Abra": { "release_below_cp": 208, "release_below_iv": 0.8, "logic": "and" },
      "Zubat": { "release_below_cp": 225, "release_below_iv": 0.8, "logic": "and" },
      "Chansey": { "release_below_cp": 235, "release_below_iv": 0.8, "logic": "and" },
      "Pidgey": { "release_below_cp": 237, "release_below_iv": 0.8, "logic": "and" },
      "Spearow": { "release_below_cp": 240, "release_below_iv": 0.8, "logic": "and" },
      "Meowth": { "release_below_cp": 264, "release_below_iv": 0.8, "logic": "and" },
      "Krabby": { "release_below_cp": 276, "release_below_iv": 0.8, "logic": "and" },
      "Sandshrew": { "release_below_cp": 278, "release_below_iv": 0.8, "logic": "and" },
      "Poliwag": { "release_below_cp": 278, "release_below_iv": 0.8, "logic": "and" },
      "Horsea": { "release_below_cp": 278, "release_below_iv": 0.8, "logic": "and" },
      "Gastly": { "release_below_cp": 280, "release_below_iv": 0.8, "logic": "and" },
      "Ekans": { "release_below_cp": 288, "release_below_iv": 0.8, "logic": "and" },
      "Shellder": { "release_below_cp": 288, "release_below_iv": 0.8, "logic": "and" },
      "Vulpix": { "release_below_cp": 290, "release_below_iv": 0.8, "logic": "and" },
      "Voltorb": { "release_below_cp": 292, "release_below_iv": 0.8, "logic": "and" },
      "Geodude": { "release_below_cp": 297, "release_below_iv": 0.8, "logic": "and" },
      "Doduo": { "release_below_cp": 297, "release_below_iv": 0.8, "logic": "and" },
      "Onix": { "release_below_cp": 300, "release_below_iv": 0.8, "logic": "and" },
      "Mankey": { "release_below_cp": 307, "release_below_iv": 0.8, "logic": "and" },
      "Pikachu": { "release_below_cp": 309, "release_below_iv": 0.8, "logic": "and" },
      "Magnemite": { "release_below_cp": 312, "release_below_iv": 0.8, "logic": "and" },
      "Tentacool": { "release_below_cp": 316, "release_below_iv": 0.8, "logic": "and" },
      "Paras": { "release_below_cp": 319, "release_below_iv": 0.8, "logic": "and" },
      "Jigglypuff": { "release_below_cp": 321, "release_below_iv": 0.8, "logic": "and" },
      "Ditto": { "release_below_cp": 321, "release_below_iv": 0.8, "logic": "and" },
      "Staryu": { "release_below_cp": 326, "release_below_iv": 0.8, "logic": "and" },
      "Charmander": { "release_below_cp": 333, "release_below_iv": 0.8, "logic": "and" },
      "Goldeen": { "release_below_cp": 336, "release_below_iv": 0.8, "logic": "and" },
      "Squirtle": { "release_below_cp": 352, "release_below_iv": 0.8, "logic": "and" },
      "Cubone": { "release_below_cp": 352, "release_below_iv": 0.8, "logic": "and" },
      "Venonat": { "release_below_cp": 360, "release_below_iv": 0.8, "logic": "and" },
      "Bulbasaur": { "release_below_cp": 374, "release_below_iv": 0.8, "logic": "and" },
      "Drowzee": { "release_below_cp": 374, "release_below_iv": 0.8, "logic": "and" },
      "Machop": { "release_below_cp": 381, "release_below_iv": 0.8, "logic": "and" },
      "Psyduck": { "release_below_cp": 386, "release_below_iv": 0.8, "logic": "and" },
      "Seel": { "release_below_cp": 386, "release_below_iv": 0.8, "logic": "and" },
      "Kabuto": { "release_below_cp": 386, "release_below_iv": 0.8, "logic": "and" },
      "Bellsprout": { "release_below_cp": 391, "release_below_iv": 0.8, "logic": "and" },
      "Omanyte": { "release_below_cp": 391, "release_below_iv": 0.8, "logic": "and" },
      "Kadabra": { "release_below_cp": 396, "release_below_iv": 0.8, "logic": "and" },
      "Oddish": { "release_below_cp": 400, "release_below_iv": 0.8, "logic": "and" },
      "Dugtrio": { "release_below_cp": 408, "release_below_iv": 0.8, "logic": "and" },
      "Rhyhorn": { "release_below_cp": 412, "release_below_iv": 0.8, "logic": "and" },
      "Clefairy": { "release_below_cp": 420, "release_below_iv": 0.8, "logic": "and" },
      "Slowpoke": { "release_below_cp": 424, "release_below_iv": 0.8, "logic": "and" },
      "Pidgeotto": { "release_below_cp": 427, "release_below_iv": 0.8, "logic": "and" },
      "Farfetch'd": { "release_below_cp": 441, "release_below_iv": 0.8, "logic": "and" },
      "Poliwhirl": { "release_below_cp": 468, "release_below_iv": 0.8, "logic": "and" },
      "Nidorino": { "release_below_cp": 480, "release_below_iv": 0.8, "logic": "and" },
      "Haunter": { "release_below_cp": 482, "release_below_iv": 0.8, "logic": "and" },
      "Nidorina": { "release_below_cp": 489, "release_below_iv": 0.8, "logic": "and" },
      "Graveler": { "release_below_cp": 501, "release_below_iv": 0.8, "logic": "and" },
      "Beedrill": { "release_below_cp": 504, "release_below_iv": 0.8, "logic": "and" },
      "Raticate": { "release_below_cp": 504, "release_below_iv": 0.8, "logic": "and" },
      "Butterfree": { "release_below_cp": 508, "release_below_iv": 0.8, "logic": "and" },
      "Hitmonlee": { "release_below_cp": 520, "release_below_iv": 0.8, "logic": "and" },
      "Ponyta": { "release_below_cp": 530, "release_below_iv": 0.8, "logic": "and" },
      "Hitmonchan": { "release_below_cp": 530, "release_below_iv": 0.8, "logic": "and" },
      "Charmeleon": { "release_below_cp": 544, "release_below_iv": 0.8, "logic": "and" },
      "Wartortle": { "release_below_cp": 552, "release_below_iv": 0.8, "logic": "and" },
      "Persian": { "release_below_cp": 568, "release_below_iv": 0.8, "logic": "and" },
      "Lickitung": { "release_below_cp": 568, "release_below_iv": 0.8, "logic": "and" },
      "Ivysaur": { "release_below_cp": 571, "release_below_iv": 0.8, "logic": "and" },
      "Electrode": { "release_below_cp": 576, "release_below_iv": 0.8, "logic": "and" },
      "Marowak": { "release_below_cp": 578, "release_below_iv": 0.8, "logic": "and" },
      "Gloom": { "release_below_cp": 590, "release_below_iv": 0.8, "logic": "and" },
      "Porygon": { "release_below_cp": 590, "release_below_iv": 0.8, "logic": "and" },
      "Seadra": { "release_below_cp": 597, "release_below_iv": 0.8, "logic": "and" },
      "Jynx": { "release_below_cp": 600, "release_below_iv": 0.8, "logic": "and" },
      "Weepinbell": { "release_below_cp": 602, "release_below_iv": 0.8, "logic": "and" },
      "Tangela": { "release_below_cp": 607, "release_below_iv": 0.8, "logic": "and" },
      "Fearow": { "release_below_cp": 609, "release_below_iv": 0.8, "logic": "and" },
      "Parasect": { "release_below_cp": 609, "release_below_iv": 0.8, "logic": "and" },
      "Machoke": { "release_below_cp": 614, "release_below_iv": 0.8, "logic": "and" },
      "Arbok": { "release_below_cp": 616, "release_below_iv": 0.8, "logic": "and" },
      "Sandslash": { "release_below_cp": 631, "release_below_iv": 0.8, "logic": "and" },
      "Alakazam": { "release_below_cp": 633, "release_below_iv": 0.8, "logic": "and" },
      "Kingler": { "release_below_cp": 636, "release_below_iv": 0.8, "logic": "and" },
      "Dodrio": { "release_below_cp": 640, "release_below_iv": 0.8, "logic": "and" },
      "Tauros": { "release_below_cp": 643, "release_below_iv": 0.8, "logic": "and" },
      "Primeape": { "release_below_cp": 650, "release_below_iv": 0.8, "logic": "and" },
      "Magneton": { "release_below_cp": 657, "release_below_iv": 0.8, "logic": "and" },
      "Venomoth": { "release_below_cp": 660, "release_below_iv": 0.8, "logic": "and" },
      "Golbat": { "release_below_cp": 672, "release_below_iv": 0.8, "logic": "and" },
      "Raichu": { "release_below_cp": 708, "release_below_iv": 0.8, "logic": "and" },
      "Cloyster": { "release_below_cp": 717, "release_below_iv": 0.8, "logic": "and"},
      "Mr. Mime": { "release_below_cp": 650, "release_below_iv": 0.8, "logic": "and" }
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}
`

**Comment by JelleDRC** [comment]
I have the same issue. Same task order (default)

**Comment by LeonJansen** [comment]
It also never reaches a Fort, it is walkin away from them, and then decides to go to another fort, and also walking away from it. This process keeps on repeating.

**Comment by tstumm** [comment]
Please try to to the following:
Add `return False` right below `sleep(1)` in `pokemongo_bot/step_walker.py`

**Comment by Bashin** [comment]
#2192 
At least a workaround for now

**Comment by LeonJansen** [comment]
@tstumm I added `return False` but it still does the same thing. I'm trying @Bashin workaround now.

**Comment by LeonJansen** [comment]
Ok i can Confirm that the workaround from @Bashin is working, i removed FollowSpiral from the config, and now the bot is walking towards the Fort again, and is not doing random stuff. So i can agree that there is something buggy with the FollowSpiral.

**Comment by tstumm** [comment]
If you fully replace `StepWalker` by this:
```
from cell_workers.utils import distance
from human_behaviour import random_lat_long_delta, sleep


class StepWalker(object):

    def __init__(self, bot, speed, dest_lat, dest_lng):
        self.bot = bot
        self.api = bot.api

        self.speed = speed

        self.destLat = dest_lat
        self.destLng = dest_lng


    def step(self):
        self.dist = distance(
            self.self.bot.position[0],
            self.self.bot.position[1],
            self.dest_lat,
            self.dest_lng
        )

        self.steps = (self.dist + 0.0) / (self.speed + 0.0)

        if (self.dLat == 0 and self.dLng == 0) or self.dist < self.speed or int(self.steps) <= 1:
            self.api.set_position(self.destLat, self.destLng, 0)
            return True
        else:
            self.dLat = (self.dest_lat - self.initLat) / int(self.steps)
            self.dLng = (self.dest_lng - self.initLng) / int(self.steps)

        cLat = self.initLat + self.dLat + random_lat_long_delta()
        cLng = self.initLng + self.dLng + random_lat_long_delta()

        self.api.set_position(cLat, cLng, 0)
        self.bot.heartbeat()

        sleep(1)
        return False
```
does it work then?

**Comment by LeonJansen** [comment]
@tstumm your code appears to have some bugs in it, it is not working.

**Comment by tstumm** [comment]
Sorry I fixed it in the code above.

**Comment by LeonJansen** [comment]
Nope still not working:

`from cell_workers.utils import distance
from human_behaviour import random_lat_long_delta, sleep


class StepWalker(object):

    def __init__(self, bot, speed, dest_lat, dest_lng):
        self.bot = bot
        self.api = bot.api

        self.speed = speed

        self.destLat = dest_lat
        self.destLng = dest_lng


    def step(self):
        self.dist = distance(
            self.bot.position[0],
            self.bot.position[1],
            self.dest_lat,
            self.dest_lng
        )

        self.steps = (self.dist + 0.0) / (self.speed + 0.0)

        if (self.dLat == 0 and self.dLng == 0) or self.dist < self.speed or int(self.steps) <= 1:
            self.api.set_position(self.destLat, self.destLng, 0)
            return True
        else:
            self.dLat = (self.dest_lat - self.initLat) / int(self.steps)
            self.dLng = (self.dest_lng - self.initLng) / int(self.steps)

        cLat = self.initLat + self.dLat + random_lat_long_delta()
        cLng = self.initLng + self.dLng + random_lat_long_delta()

        self.api.set_position(cLat, cLng, 0)
        self.bot.heartbeat()

        sleep(1)
        return False`

**Comment by tstumm** [comment]
Now it should work lol

**Comment by tstumm** [comment]
Nevermind we found the problematic code, it has something to do with Niantic doing throttling.

**Comment by LeonJansen** [comment]
Ok, is it something that can be fixed in the code?

**Comment by tstumm** [comment]
Yes, we get empty responses sometimes.

**Comment by AlexBailey** [comment]
I think this is also the same as my issue thread here too: https://github.com/PokemonGoF/PokemonGo-Bot/issues/2131
