### ISSUE TITLE
UnboundLocalError from variable 'position'

### ISSUE THREAD

**Issue by surfaace** [PokemonGoF/PokemonGo-Bot#220]
### Expected Behavior
position should be set before calling array

### Actual Behavior
Arrived at Pokestop
Now at Pokestop: Riksdagslejontv├Ñ - Spinning...
- Loot:
- 50 xp
- 1x Pokeball
- 1x Pokeball
- 1x Razz Berry
- PokeStop on cooldown. Time left: 299.161999941 seconds.
Found fort 30e2a68d345441f2abfa141a964deabd.16 at distance 4.87814204604m
Traceback (most recent call last):
  File "D:\Pokemon stuff\PokemonGo-Bot\pokecli.py", line 120, in <module>
    main()
  File "D:\Pokemon stuff\PokemonGo-Bot\pokecli.py", line 117, in main
    bot.take_step()
  File "D:\Pokemon stuff\PokemonGo-Bot\bot.py", line 30, in take_step
    self.stepper.take_step()
  File "D:\Pokemon stuff\PokemonGo-Bot\stepper.py", line 49, in take_step
    self.bot.work_on_cell(cell,position)
  File "D:\Pokemon stuff\PokemonGo-Bot\bot.py", line 59, in work_on_cell
    hack_chain = worker.work()
  File "D:\Pokemon stuff\PokemonGo-Bot\cell_workers\seen_fort_worker.py", line 36, in work
    self.api.fort_details(fort_id=self.fort['id'], latitude=position[0], longitude=position[1])
UnboundLocalError: local variable 'position' referenced before assignment

### Steps to Reproduce
Always after two pokestops using location starting location 59.328569,18.064374 this error occure

### Other Information
OS: Win 10 pro x64
Git Commit: ebb8dba06e94fb0addb15b634124edc2079ec87a

**Comment by surfaace** [comment]
Also exists on dev branch, c80ab0d70475f2faa8407d1318152f9cd8f73f2f

**Comment by douglascamata** [comment]
Fixed in dev already. Thanks!

**Comment by surfaace** [comment]
Problem persists in dev:

[#] Found fort 30e2a68d345441f2abfa141a964deabd.16 at distance 4.87814204604m
Traceback (most recent call last):
  File "D:\Pokemon stuff\PokemonGo-Bot\pokecli.py", line 107, in <module>
    main()
  File "D:\Pokemon stuff\PokemonGo-Bot\pokecli.py", line 104, in main
    bot.take_step()
  File "D:\Pokemon stuff\PokemonGo-Bot\pokemongo_bot\__init__.py", line 31, in take_step
    self.stepper.take_step()
  File "D:\Pokemon stuff\PokemonGo-Bot\pokemongo_bot\stepper.py", line 58, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "D:\Pokemon stuff\PokemonGo-Bot\pokemongo_bot\stepper.py", line 103, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "D:\Pokemon stuff\PokemonGo-Bot\pokemongo_bot\__init__.py", line 54, in work_on_cell
    hack_chain = worker.work()
  File "D:\Pokemon stuff\PokemonGo-Bot\pokemongo_bot\cell_workers\seen_fort_worker.py", line 43, in work
    self.api.fort_details(fort_id=self.fort['id'], latitude=position[0], longitude=position[1])
UnboundLocalError: local variable 'position' referenced before assignment


git commit: 6199d496d37b40a5ec9bfda0d4fb69c93b44a6cd
