### ISSUE TITLE
Requirements install problem

### ISSUE THREAD

**Issue by Drambuie** [PokemonGoF/PokemonGo-Bot#2717]
### Expected Behavior

expect xxhash to install

### Actual Behavior

recieving the following error

.replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-XCevGC-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'xxhash' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/xxhash
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DVERSION=0.6.1 -I/usr/include/python2.7 -c python-xxhash.c -o build/temp.linux-x86_64-2.7/python-xxhash.o -std=c99 -O3 -Wall -W -Wundef -Wno-error=declaration-after-statement
    python-xxhash.c:31:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-khdMHg/xxhash/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-XCevGC-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-khdMHg/xxhash/

### Steps to Reproduce

sudo pip install -r requirements.txt

### Other Information
OS: UBUNTU
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by frossaren** [comment]
Same problem here. Following

**Comment by B3H1NDu** [comment]
As above. I tried updating, here is a dump when I try and run the program.
```
Traceback (most recent call last):
  File "C:\Users\Keith\Desktop\PokeBot\PokemonGo-Bot\pokecli.py", line 38, in <m
odule>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottl
ingException, ServerBusyOrOfflineException
  File "c:\users\keith\desktop\pokebot\pokemongo-bot\src\pgoapi\pgoapi\__init__.
py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "c:\users\keith\desktop\pokebot\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py
", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "c:\users\keith\desktop\pokebot\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.p
y", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff,
Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash
, f2i
  File "c:\users\keith\desktop\pokebot\pokemongo-bot\src\pgoapi\pgoapi\utilities
.py", line 30, in <module>
    import xxhash
ImportError: No module named xxhash

C:\Users\Keith\Desktop\PokeBot\PokemonGo-Bot>
```
Thanks.

**Comment by ferbeb** [comment]
Try installing package python-dev. Had the same error (python.h) for another dependency a week ago, fixed by installing python-dev. Created a issue to help other people encountering this problem but the issue was closed after no activity for like a week.

**Comment by B3H1NDu** [comment]
Will check later fer, thanks!

**Comment by Drambuie** [comment]
Resolved.....Thanks

**Comment by Sijmenjeromkok** [comment]
How did you resolve this? I still get the same error:

Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "/Users/jeromkok/htdocs/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/Users/jeromkok/htdocs/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/Users/jeromkok/htdocs/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "/Users/jeromkok/htdocs/PokemonGo-Bot/src/pgoapi/pgoapi/utilities.py", line 30, in <module>
    import xxhash
ImportError: No module named xxhash

Thanks :)

**Comment by ferbeb** [comment]
@Sijmenjeromkok 
The module is still not installed, you need to install requirements again after installing python-dev to now successfully build the xxhash module.

**Comment by Sijmenjeromkok** [comment]
Thank you Ferbeb, will try!

**Comment by g2384** [comment]
`pip install xxhash`
also, I think you need `raven` as well. `pip install raven`

**Comment by tankitty** [comment]
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 50, in <module>
    from POGOProtos.Networking.Envelopes_pb2 import RequestEnvelope
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/protos/POGOProtos/Networking/Envelopes_pb2.py", line 16, in <module>
    from POGOProtos.Networking import Requests_pb2 as POGOProtos_dot_Networking_dot_Requests__pb2
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/protos/POGOProtos/Networking/Requests_pb2.py", line 23, in <module>
    ENCOUNTER\x10\x91\x01\x12!\n\x1c\x43OLLECT_DAILY_DEFENDER_BONUS\x10\x92\x01\x12\x14\n\x0fUPGRADE_POKEMON\x10\x93\x01\x12\x19\n\x14SET_FAVORITE_POKEMON\x10\x94\x01\x12\x15\n\x10NICKNAME_POKEMON\x10\x95\x01\x12\x10\n\x0b\x45QUIP_BADGE\x10\x96\x01\x12\x19\n\x14SET_CONTACT_SETTINGS\x10\x97\x01\x12\x15\n\x10GET_ASSET_DIGEST\x10\xac\x02\x12\x16\n\x11GET_DOWNLOAD_URLS\x10\xad\x02\x12\x1c\n\x17GET_SUGGESTED_CODENAMES\x10\x91\x03\x12\x1d\n\x18\x43HECK_CODENAME_AVAILABLE\x10\x92\x03\x12\x13\n\x0e\x43LAIM_CODENAME\x10\x93\x03\x12\x0f\n\nSET_AVATAR\x10\x94\x03\x12\x14\n\x0fSET_PLAYER_TEAM\x10\x95\x03\x12\x1b\n\x16MARK_TUTORIAL_COMPLETE\x10\x96\x03\x12\x16\n\x11LOAD_SPAWN_POINTS\x10\xf4\x03\x12\t\n\x04\x45\x43HO\x10\x9a\x05\x12\x1b\n\x16\x44\x45\x42UG_UPDATE_INVENTORY\x10\xbc\x05\x12\x18\n\x13\x44\x45\x42UG_DELETE_PLAYER\x10\xbd\x05\x12\x17\n\x12SFIDA_REGISTRATION\x10\xa0\x06\x12\x15\n\x10SFIDA_ACTION_LOG\x10\xa1\x06\x12\x18\n\x13SFIDA_CERTIFICATION\x10\xa2\x06\x12\x11\n\x0cSFIDA_UPDATE\x10\xa3\x06\x12\x11\n\x0cSFIDA_ACTION\x10\xa4\x06\x12\x11\n\x0cSFIDA_DOWSER\x10\xa5\x06\x12\x12\n\rSFIDA_CAPTURE\x10\xa6\x06\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'

**Comment by phoenix98787** [comment]
Hey all,

had the same issue 

Just install Microsoft Visual C++ Compiler for Python 2.7

https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266

**Comment by TGM** [comment]
# I don't know witch one is, so feel free to identify it.
sudo apt-get install build-essential autoconf libtool pkg-config python-opengl python-imaging python-pyrex python-pyside.qtopengl idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script libqt4-network libqt4-dbus python-qt4 python-qt4-gl libgle3 python-dev

**Comment by ferbeb** [comment]
@TGM 
Like I already posted, it's `python-dev`
