### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by YvesHenri** [PokemonGoF/PokemonGo-Bot#3194]
Please check configuration at http://jsonlint.com/ before posting an issue.

### Expected Behavior
Log in and start the tasks loop

### Actual Behavior
Log in and crash (sometimes it doesnt even start the very first task, sometimes it tries to catch a pokemon).

Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
IndexError: list index out of range

### Steps to Reproduce
Log in (python pokecli.py...)

### Other Information
OS: Windows 10
Git Commit: dee28d9fb1a973b95019bc07fb1e206872bd986d
Python Version: 2.7.12

**Comment by lifez** [comment]
Same here

2016-08-09 09:46:05,289 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
IndexError: list index out of range

**Comment by tb87** [comment]
+1 ... looks like there has been another change.

**Comment by bernardoVale** [comment]
Same here using Docker containers

**Comment by shivamkalra** [comment]
Related: https://github.com/PokemonGoF/PokemonGo-Bot/issues/3193

**Comment by shivamkalra** [comment]
Below should fix it:

```
pip uninstall pgoapi && pip install -e git+https://github.com/keyphact/pgoapi.git#egg=pgoapi
```

**Comment by YvesHenri** [comment]
I was looking at issue #3193 but unfortunately the above snippet doesnt solve this issue. I'm not really convinced its related to their servers. It might just be another API change...

**Comment by kesfaw** [comment]
Try to take a rest in 10 minutes then start bot again. It has been working to me.

**Comment by rootbeersoup** [comment]
Getting this same issue. I installed the new pgoapi and it didn't fix anything, but the bot ended up running a few minutes later anyway. I'm guessing it's a server issue.

**Comment by shivamkalra** [comment]
Try `dev` branch if issue persists? It is currently happening on one of my bot account but it fixed itself after 10 mins rest like @kesfaw  said. Also for precaution, can you try temporary fix in: #3176

**Comment by kesfaw** [comment]
[Additional information]
I have two working bots but I only got this error on the bot having config with task type "FollowPath". 
As a fact, the error message we got is also refer to a certain list out range ~> "IndexError: list index out of range". 

Does it has any relation?

**Comment by shivamkalra** [comment]
@kesfaw Try changing your working bot to have same config as your non working bot (just exchange account info). If it is because of FollowPath then create additional ticket and refer this ticket.

**Comment by kesfaw** [comment]
Okay @shivamkalra.  I'll try next error catching.

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
