### ISSUE TITLE
**META** Soft bans - Try again spins / Pokemon vanishing 

### ISSUE THREAD

**Issue by Coburnss** [PokemonGoF/PokemonGo-Bot#3700]
# Edited by moderator:

## Other current META issues:
#3682 - [**META** Server busy or offline issues](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3682)
#3308 - [**META** Stuck between two forts / Moving to 2 forts at the same time / Constant Loop](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3308)
#3700 - [**META** Soft bans - Try again spins / Pokemon vanishing](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3700)
#3746 - [**META** Banwaves - Permanent Bans](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3746)

**Comment by SilverDragon135** [comment]
Same here, but it my case it seems like soft ban fix works just temporally: 
![image](https://cloud.githubusercontent.com/assets/17603598/17616574/f3465a8a-6075-11e6-8717-62049cd1032c.png)

**Comment by SilverDragon135** [comment]
And sometimes bot stucks on: 
![image](https://cloud.githubusercontent.com/assets/17603598/17616751/78b8d7a6-6076-11e6-8c54-0cb6de4669bf.png)

**Comment by takenek** [comment]
I just get ban for IP address :-( Cant login to account :-(

**Comment by Coburnss** [comment]
Mine isn't a ip ban, nor a full ban that has been addressed because I can login to other accounts. Just the usual disappearing Pokémon, but I'm used to just spinning the Pokestops to remedy, which can no longer be done, at least by me.

**Comment by maxprzemo** [comment]
`Login successful.2016-08-12 10:57:54,550 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again `
ban forever?

**Comment by Coburnss** [comment]
Seeming as though. But past full bans were addressed with a screen that told you just that. This seems like server issues, or a truly new soft ban. Guess time will tell.

**Comment by PierceJhuang** [comment]
I got the same issue in Taiwan, is it a server issue? but my friend still can get item from pokenstop...

**Comment by Coburnss** [comment]
My Google Account is working fine with the script. My Poke account however is not. So if it is server side it must just be Pokémon Go accounts.

**Comment by rickycc** [comment]
I just encountered this. Login with phone failed to see any pokestops nor pokemons.

`[10:37:26] Pokestop Ancient Chinese Sculpture out of range.
[10:37:26] Possibly searching too often, take a rest.
[10:37:26] Moving towards pokestop Metro Theater - 0.09km
[10:37:26] {'distance_unit': '', 'distance': '', 'current_position': (37.79756671816564, -122.43231646990498), 'last_position': (37.79760335969092, -122.43217462756321)}
[10:37:30] Moving towards pokestop Metro Theater - 0.08km
[10:37:30] {'distance_unit': '', 'distance': '', 'current_position': (37.79750192054127, -122.43247259938424), 'last_position': (37.79756671816564, -122.43231646990498)}
[10:37:31] Moving towards pokestop Metro Theater - 0.06km
[10:37:31] {'distance_unit': '', 'distance': '', 'current_position': (37.79745142750385, -122.43265642107315), 'last_position': (37.79750192054127, -122.43247259938424)}
[10:37:34] Moving towards pokestop Metro Theater - 0.05km
[10:37:34] {'distance_unit': '', 'distance': '', 'current_position': (37.797406834408584, -122.43283736090339), 'last_position': (37.79745142750385, -122.43265642107315)}
[10:37:36] Pokestop Metro Theater out of range.
[10:37:36] Possibly searching too often, take a rest.
[10:37:37] Moving towards pokestop Collectors Cave - 0.05km
[10:37:37] {'distance_unit': '', 'distance': '', 'current_position': (37.79742262424499, -122.43303676942789), 'last_position': (37.797406834408584, -122.43283736090339)}
[10:37:40] Pokestop Collectors Cave out of range.
[10:37:40] Possibly searching too often, take a rest.
[10:37:40] Moving towards pokestop Original Temple, Vedanta Socie - 0.13km
[10:37:40] {'distance_unit': '', 'distance': '', 'current_position': (37.79751969419062, -122.43316814837154), 'last_position': (37.79742262424499, -122.43303676942789)}
[10:37:42] Moving towards pokestop Original Temple, Vedanta Socie - 0.11km
[10:37:42] {'distance_unit': '', 'distance': '', 'current_position': (37.79761238161907, -122.43331114636779), 'last_position': (37.79751969419062, -122.43316814837154)}`

**Comment by Waliers** [comment]
Try it on you phone on cellulair instead of wifi. If you see the pokestops when not on WiFi you ip is (soft)banned.

**Comment by Coburnss** [comment]
I'm not IP banned. I have switched from cellular to wifi, and haven't used the bot since it started its shit.

**Comment by fari-99** [comment]
maybe this related issue will bright you up
#3308 #3394 #3475 #3646 #3692 #3711 #3721

**Comment by k4n30** [comment]
@fari-99 steal my thunder :p

**Comment by danielsdian** [comment]
Im able to enter the game thru bluestacks, walk around, spin forts, battle gyms, but the pokemon keep vanishing.

**Comment by cnoekkii** [comment]
Any solutions yet?

**Comment by danielsdian** [comment]
I tried reducing walk speed to 4 and increased the wait times. Didnt change anything. I spinned the pokestops 40 times too.

**Comment by YvesHenri** [comment]
That unban trick seemed, to me, to have been fixed a long time ago. I got banned for teleporting and manually tried to unban myself, but it did not work. That's been like 2-3 weeks ago.
I don't really know what's happening, though. Been botting for a month, on 2 accounts, and unfortunatelly they got full of pokemons and couldnt catch anymore (known bug, I know). I turned them off untill I got at work and, for my surprise, one of them seemed to have been softbanned. I did not switch locations and both accounts use pretty much the same config, although the one that got 'softbanned', crashed a little ago, with a SSL error (this maybe why?). Also, I tried botting with my snipping account and it worked just fine, on the very same IP.

**Comment by danielsdian** [comment]
Wild guess: Maybe they are trying to match our location by IP and GPS?

**Comment by cnoekkii** [comment]
@danielsdian I'm was farming at central park NY, but I live in Belgium. I've used a VPN from the US, still not fixed

**Comment by k4n30** [comment]
No that's not realistic, my ISP connection is made 500km away so that should result in a ban. Also, I use a VPN on top of that which terminates in a different country. They can't ban users (or try to ensure GPS matches IP locations) for using VPNs

**Comment by izanagi1995** [comment]
I think it's more complicated than that. Before unknown6 they got a lot of data about how bots move. I think they got the trick to detect "abnormal" moves.

**Comment by chylek** [comment]
My bot moves along a path from Google's Directions Api for walking and still got banned ... I would bet on abnormal sequence/timing of requests rather than moves.

**Comment by k4n30** [comment]
From PokemonGoDev Team:

> Due to the large influx of people claiming problems with their accounts and devices, we'd like you to fill out this Google Form: https://goo.gl/forms/tjilsa8OApcjuhj82
> 
> This will help us try to pinpoint where and why the problem is happening, try to find a pattern in the problem and maybe find a solution if one exists. To see the results of this pool, you can either click See results on the Google Form once finished or by following this link: https://docs.google.com/forms/d/e/1FAIpQLScNVX6a5AkVGxyNo3kmiNIG3lHeI3dFXLa_E0F0yCOhL7C4dA/viewanalytics?usp=form_confirm
> 
> If you wish to see the answers directly, go here to see the Google Sheet: https://docs.google.com/spreadsheets/d/1Xq_W1mDxrQ8k1lXA-idv7029eOsY8PUsGcrTCrYySrE/edit?usp=sharing
> 
> Thank you

**Comment by p1n9** [comment]
Here is my little test : 
I made a teleport to be softbanned, I can't spin pokestop then the usual unban trick unsoftban me.
Now I can spin pokestops usually, I can also do battles in arena and hatch eggs.
But I can't catch pokemon, they always vanish.

I use a google account, and the symptoms are both through the bot or the app (android)

Perhaps a new type of ban, after the last niantic's api update the devs that have cracked it says they found a potential flag about cheating players.

Wait and see....

**Comment by p1n9** [comment]
@k4n30 IT'S A TRAP !

**Comment by YvesHenri** [comment]
This is the last thing I got before this situation: http://pastebin.com/CUPprGeg. After retrying, it got banned.

**Comment by qinidema** [comment]
I think this is really IP(ISP)-based. Experienced a soft ban yesterday (no pokemons, no pokestops, just an empty map). Then changed network connection to 3G provider and voila - all goes just fine.
Another 5 cents to this theory - ISP check is easily implemented server-side. Consider that you want to detect cheaters. You can do it the hard way:
1) Remember last N previous coordinates, then build the pathway to detect movement anomalies
2) Rememer last looted pokestops to detect "hey, this guy just goes from one fort to another and collects all the items for the matter of milliseconds"
3) Calculate successfully caught pokemon rates per hour (we also need to remember all tries and catches for the last time)
4) etc.
VS
"we just do a quick ISP-by-IP lookup with small library and ready-to-use collected database"
So, which method is easier implemented, works faster (server-side) and requires less memory on already overloaded servers? I think that the answer is obvious.

So running just fine here. No teleporting, realistic speed (lower that 5 km/h), short distances (below 15 km per run) - and you should be going just fine to my mind.

**Comment by AutopsyMania** [comment]
I switched to my real phone device and using Pokomon Go App. Tried to throw away (not hitting pokemon) 45 pokeballs and the the pokemons still got vanishing. Manual unban methods does not work for me.

**Comment by nujabse** [comment]
Maybe the server has a problem?

**Comment by GitPupper** [comment]
#3746

**Comment by YuMan-Tam** [comment]
Yes, doesn't work my real phone after 3-4 hours either. But I can still log in. Just seeing nothing on my phone using LTE network.

**Comment by YvesHenri** [comment]
@GitPupper why did you reference another issue ("Duplicates will be deleted without warning.")?

**Comment by YuMan-Tam** [comment]
Oh wow. Mine was actually a soft ban that cannot be fixed by the bot's "soft ban" algorithm. The Pokestop show up again after 4 hours. All seems fine for now...

**Comment by YvesHenri** [comment]
@YuMan-Tam Can you tell us what exactly happened to you, since the banning (I'm assuming youre just another)?

**Comment by danielsdian** [comment]
I really think we should put a warning in the Project page and in Slack. People is going crazy after answers and the reply is the same.

**Comment by YuMan-Tam** [comment]
@YvesHenri :  I was running the Pokemon Bot for the past 48 hours without problems until this morning. At around 6 a.m, the bot started displaying exactly the same log as @rickycc (see above - I do not know how to reference the particular post, nor did I saved my log). 

I tried to restart the bot, or use my cell phone network instead. I could always log in but the same log happened. I kept trying until 11 am when it suddenly works again on my cell phone. I will need to check the bot later today after I get home from work.

**Comment by skywalker878** [comment]
Any Update here? 
How can we fix the soft ban ? 
Looks like my account in soft banned more than 12 hours.

**Comment by Coburnss** [comment]
Honestly it's looking like a waiting game for us "Soft Bans". Thus far nothing has changed for me. I think we just need to consider ourselves lucky that we haven't gotten the email solidifying the fact we are perma'd.

**Comment by Magamar01** [comment]
After playing through the bot and having everything vanish I exited and played through the app. My softban unfolded in stages over 6 or 7 hours.
-At first I couldn't catch pokemon or spin pokestops
-About 2 hours later I could catch pokemon but couldn't spin pokestops
-A few hours after that I could play normally.

Anyone else experience something similar?

**Comment by Coburnss** [comment]
I have experienced that in the past. Seems like a standard soft ban. However I've been "Soft banned" for over 12 hours, but now it's accompanied with a Try Again Later message at every pokestop.

**Comment by kipperjx2** [comment]
I have the spin later and catch flee. I can see everything. I can fight in gyms... Is this a soft ban? Like you said will it go away incrementally?

**Comment by Coburnss** [comment]
If I were you I wouldn't use the Gyms, I haven't even checked if they work for me, I just immediately stopped the bot once I seen it malfunction. Seems to be a easy place to round up scripters and take them out.

**Comment by Coburnss** [comment]
I can confirm it was a new version of the Soft Ban, all is functioning 100% with my account at the moment. Let's all stay away from Gyms and quit teleporting to Japan and what not and I think we will be fine.

**Comment by jannickv** [comment]
Same here, could spin but all pokemon vanished... Now 100% working again! New type of softban!

**Comment by danielsdian** [comment]
Its working for me now too!

**Comment by kipperjx2** [comment]
I'm back in as well

**Comment by TCB13** [comment]
@danielsdian and @jannickv I'm running into the same problem you did. I CAN spin stops but all pokemon just vanish.

**Comment by LDengXYZ** [comment]
My Softban (can collect item but pokemon flee) has just turned into Hard ban (cannot login). 

Interestingly, it happened as soon as I deleted the ios app and re-install then login. 
A few mins ealier (before I reinstall the app), I was able to login.

**Comment by kipperjx2** [comment]
Dang, rip

**Comment by YvesHenri** [comment]
I've been following this since this morning. I'm one of those who had stuff fleeing all the time, but it looks like it is 'fixed' (everything back to what it used to be) now. Gonna bot again. lol

**Comment by kipperjx2** [comment]
Your gonna risk getting banned!? Just stick to spoofing!? Jeez living dangerously..

**Comment by tolinwei** [comment]
@YvesHenri Yeah I've also been following this for the whole days, same "new" soft ban, just fixed automatically 10 min ago, I'm able to catch Pokemon now. (I heard some others were fixed like a hour ago)

But I'm not gonna continue to use this not for my main account unless I hear some further news. Will continue to try out using new accounts probably.

**Comment by lmondry** [comment]
Just saw that on another bot issue section :

> I believed that because bot throw too many excellent balls, so it active the softban, so just find one pokemon throw 50 balls don't hit that pokemon, then it will unban. It works for me and my friends, hope it work for you

Maybe this could help 

[https://github.com/jabbink/PokemonGoBot/issues/1039](url)

**Comment by mico** [comment]
@LDengXYZ I've got hard ban too. Just logged in with bot after using ios app and got it immediately. I had 25 lvl and had fighting at gyms before.

**Comment by LDengXYZ** [comment]
@mico But were you softban first before hardban? Or you got hardban directly?

 I've never fought a gym,!I haven't even select a team yet.

**Comment by YvesHenri** [comment]
@mico that lead us to think theres a flaw in the API. Another assumption is that they did a 'simple' select on their database for suspicious values and checked this github, discord, reddit and slack to see if they really hit us, thats why they 'soft' banned us, just in case they did something wrong, legit users would stay safe. Seriously, I highly believe in this.

**Comment by guibr321** [comment]
## I was using the boot during 3 hours and everything was OK. Suddenly pokemon started running away without no reason for 5 minutes. Then I reboot the bot and now everything is OK again...
THAT'S WEIRD DUDE!

**Comment by GrosCep** [comment]
Hey, just to add one more feed back.

I am in France, played with one bot on one account for one week on one computer with one fix IP adress and I was at level 28 before getting a hard ban, I think, yesterday afternoon (busy servers). And I teleported a lot all around Europe.

I created a new account juste after seeing this, same computer, same IP, but no teleportation greater than 300m. It ran for 20 hours non stop, reached level 21, and had then the problem of vanishing pokemons. Pokestops are ok, on my phone and on the computer.

**Comment by TCB13** [comment]
@guibr321  I noticed the same thing here, however after a reboot can't still catch pokemon.

**Comment by jrjhealey** [comment]
I saw an article the other day that said niantic have done a huge ban wave, including IP bans and so on, not just softbans.

**Comment by kurazli** [comment]
@jrjhealey can you provide a link to the article please?

**Comment by jrjhealey** [comment]
I couldn't find the exact one as I lost the link on Facebook somewhere, but there is this. I'm making no claims about its credibility though.

http://www.theverge.com/2016/8/12/12461136/pokemon-go-niantic-permanent-game-ban-cheating-bots

Additionally, Niantic apparently created a ban appeal page shortly before the banwave and there is a lot of discussion on reddit about it.

**Comment by kurazli** [comment]
@jrjhealey thank you

**Comment by tolinwei** [comment]
Some new report! My main account was "new" soft banned around 7:30am yesterday, and was fixed by Niantic in the afternoon. Then last night, I created a new account to run with bot, and now I just checked that account, it's 22 lvl now and got "old" soft banned (no Pokestop spin and all Pokemons vanished).

**Seems the bot is not safe any more**, anyone has similar situation as me (try to use bot after yesterday's banwave and got banned again)?

**Comment by kurazli** [comment]
@tolinwei what do dou mean by "fixed by niantic"? did you ask them to?

**Comment by tolinwei** [comment]
@kurazli No, they recovered many accounts yesterday afternoon, even recovered some of the perm banned account (I heard this from on of my friends).

**Comment by TCB13** [comment]
@tolinwei what's your timezone. I was in the new softban yesterday and it get fixed late night like 3 am GMT+1.

**Comment by kienthoang** [comment]
I got the "new soft ban" too (can get stuff from Pokestops but all pokemons flee). I was able to unlift the ban by just going outside with my phone and threw 50 pokeballs (all missed) at the first pokemon I see. I was able to catch pokemon fine afterward.

**Comment by TCB13** [comment]
@kienthoang tried that, no luck.

**Comment by tolinwei** [comment]
@TCB13 I'm in PDT (California). I've been following this issue and https://github.com/PokemonGoF/PokemonGo-Bot/issues/3746#issuecomment-239611706 the whole yesterday. My account was recovered 1+ hours after I saw someone else in this issue said their account was recovered.

**Comment by TCB13** [comment]
@tolinwei 3AM GMT = 7PM PDT, is it a match...?

**Comment by TCB13** [comment]
So, I kept spinning pokestops after the "new soft ban" and right now I can login to the game. Bot says "server busy" the App says "failed to get game data from server".

**Comment by izanagi1995** [comment]
Server busy = hard ban

**Comment by GrosCep** [comment]
As I told it in a previous comment, it doesn't seem to be IP related.
On the same computer, with the same IP, my first account, with a lot of teleporting in different countries, has been closed since yesterday. 
The new one I created yesterday, has been soft ban (pokemons vanishing) at level 21 (in one run) during ca. 12 hours today, but now works normally (teleporting in my city only). I use it with the same computer and the same IP.

**Comment by Wolfvarine** [comment]
I had "try again later" at pokestops and "error" at the gyms, i just threw 50 pokeballs to the side, logged off for 10min,logged bk on and it was fixed

**Comment by k4n30** [comment]
https://www.reddit.com/r/pokemongodev/comments/4xkqmq/new_ban_types_and_their_causes/

**Comment by avexus** [comment]
1) I would like to know how to change IP.
2) Is it safe to use bot now?
Any ideas?

**Comment by YvesHenri** [comment]
@Wolfvarine What happened afterwards? Are you still unbanned? It looks like (bot crashed and first pokemon encounter, it was vanished, so I immediatelly closed it) I got that "new" soft ban (again) on my main, so I just throwed some balls, like people say, and apparently I got it unbanned but now I'm afraid I'll get perma ban.

**Comment by YuMan-Tam** [comment]
I am using the bot fine without problems. Just walk slower and do not teleport, for now. If you are able to log-in, then it should be soft ban. Otherwise, it's permanent (seems).

**Comment by YvesHenri** [comment]
One more report: so, I've had 2 accounts: a main and an alt. The alt has been 'newly' soft banned and 1 day later, it got perma banned (removed). That all happened after my bot has crashed, with this following error message: http://pastebin.com/3uL84JZZ
Yesterday, I noticed the bot crashed again, this time, on my main account, with an error nearly as close to the one I listed above. After reconnecting, the first pokemon has vanished instantly and I immediately closed it. Logged on my phone, threw 50 balls away and it seemed to 'fix' the possibly ban. I am now afraid to get perma banned or whatsoever. lol

**Comment by YuMan-Tam** [comment]
@YvesHenri: 

Same thing happened to me yesterday. Although I stopped botting for a day, and it's fine logging in using my cellphone from work, I got banned when I tried to log in again using my cellphone at home. Seems that they went over the historical data to ban people or something.

**Comment by YvesHenri** [comment]
@YuMan-Tam what kind of ban you were "banned again"? Perma or "new"?

**Comment by YuMan-Tam** [comment]
@YvesHenri : 

The permanent one it seems. I cannot log in. The funny thing is that I did not use the bot for the past 12 hours, and I used my cell phone to successfully log in several times before I was banned after getting home from work.

I could only infer that the company perhaps retroactively ban people!

**Comment by YvesHenri** [comment]
It's about time my time will come, then. :'(
I read somewhere that theyre banned everyone above 34. Right now, I need only 50k to 35. What level where you?

**Comment by YuMan-Tam** [comment]
@YvesHenri : 

I am just barely pass level 32. Good luck to you!

**Comment by FLUFFYBUM** [comment]
Okay so i just also got the new softban. I think after about 10min it goes into the "normal" softban we are used to. During this new softban phase i could not catch any pokemon. In addition i would get the repetitive message of try again later while spinning, each time. I am lvl 25 and "doin the dirty" as you would call it. Not sniping yet because it might be risky. Based on this thread i can tell it goes into the new softban>you wait to get unbanned>people try to bot after>gets perma banned. I don't know but could this new soft-ban wave be a new way Niantic are fishing the botters again :^(. Rip botting. I forgot to throw in, as previously stated, the bot's force unban button (pokecrot) no longer has any effect. If any one is experiencing this new type of soft ban i suggest waiting it out before botting again. Hopefully more info and experiences will be shared on this thread.

**Comment by FLUFFYBUM** [comment]
This link will clarify the new types of bans and bypasses that have been found https://www.reddit.com/r/pokemongodev/comments/4xkqmq/new_ban_types_and_their_causes/
Hope this helps! 
;^)

**Comment by k4n30** [comment]
Closing as discussion has died down if you wish to continue the discussion, please use the [banreports](https://pokemongo-bot.slack.com/messages/banreports/) channel in slack
