### ISSUE TITLE
Pokemon from Lured Pokestop do not show and therefore not possible to catch!

### ISSUE THREAD

**Issue by CheeryMom** [PokemonGoF/PokemonGo-Bot#485]
It seems that only naturally Pokemon can be detected and are possible to catch. Pokemon from lured Pokestop do not show and therefore not possible to catch. Can you or someone verify this issue and then fix this please?
Thank you!

**Comment by alistairmackenzie** [comment]
Verified, spawns from lured stops appear on the API differently which is not being picked up by the bot.

**Comment by alvin987** [comment]
Verfied, also when I enter coordinate i.e (-33.864104,151.2108361), this is what the bot show me
`[x] PokemonGO Bot v1.0
[x] Configuration initialized

[x] Address found: -33.864104, 151.2108361
[x] Position in-game set as: (-33.8642661, 151.2110302, 0.0)
`
The coordinates differences is very significant, I'm standing far away from the lure. maybe thats what makes lured pokemon seems not possible to catch

**Comment by Calcyfer** [comment]
I just fixed the coordinate issue with commit aabeace98797bac27deef65d07de2bfbe2ace4d3 , haven't been able to test if this fixes the lured pokemon, but I doubt it,

**Comment by Calcyfer** [comment]
I've started working on getting lured encounters working, will continue in the morning.

[Note to self](https://github.com/AeonLucid/POGOProtos/blob/eeccbb121b126aa51fc4eebae8d2f23d013e1cb8/src/POGOProtos/Networking/Requests/Messages/DiskEncounterMessage.proto)_

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
