### ISSUE TITLE
Latest commit treats all pokemon it see as vip

### ISSUE THREAD

**Issue by mmixx** [PokemonGoF/PokemonGo-Bot#5457]
### Expected Behavior

All below 1200 CP or 0.9 IV will not be treated as VIP pokemon.

### Actual Behavior

All pokemons it see... the bot treats it as VIP.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

http://pastebin.com/rqhT89Hp

### Output when issue occurred

```
[2016-09-16 02:43:18] [PokemonCatchWorker] [INFO] *A wild Venonat appeared!* (CP: 545) (NCP: 0.53) (Potential 0.64) (A/D/S 12/5/12)
[2016-09-16 02:43:21] [PokemonCatchWorker] [INFO] This is a VIP pokemon. Catch!!!
```
```
[2016-09-16 02:46:45] [PokemonCatchWorker] [INFO] *A wild Bellsprout appeared!* (CP: 268) (NCP: 0.24) (Potential 0.73) (A/D/S 14/9/10)
[2016-09-16 02:46:48] [PokemonCatchWorker] [INFO] This is a VIP pokemon. Catch!!!
```
```
[2016-09-16 02:50:29] [PokemonCatchWorker] [INFO] *A wild Venonat appeared!* (CP: 260) (NCP: 0.25) (Potential 0.51) (A/D/S 7/3/13)
[2016-09-16 02:50:32] [PokemonCatchWorker] [INFO] This is a VIP pokemon. Catch!!!
```

### Steps to Reproduce

Update to the latest dev commit and run the bot.

### Other Information
OS: Ubuntu 16.04
 
Branch: dev
 
Git Commit: a45943e
 
Python Version: 2.7.12
 
Any other relevant files/configs (eg: path files)

**Comment by cowst** [comment]
I confirm

**Comment by einszA** [comment]
same for me after pull from dev e209c2f82b17d418f6842772e1af8257a6a0868f

**Comment by javajohnHub** [comment]
Happening to me also. I'm looking for the cause but cannot pinpoint it.

**Comment by clubza1** [comment]
same here

**Comment by MerlionRock** [comment]
Yup... every single one = VIP....

**Comment by madzul** [comment]
same here

**Comment by rawgni** [comment]
i think it's because you did not specify charge_attack / fast attack. so it assumes that all type of attacks are VIP.

**Comment by madzul** [comment]
@rawgni why should we? isn't fast_/charge_attack is parameter in catch config? not in the vips?

**Comment by rawgni** [comment]
@madzul because the new code introduces that. the configuration in catch also affect VIP status.

@DBa2016 can you verify ? 
maybe it's better to move it separate/combine/do something to catch/vips section of the config

**Comment by madzul** [comment]
I think this issue was solved in latest pull

**Comment by db-coder** [comment]
Getting this error after latest commit:

```
Traceback (most recent call last):
  File "pokecli.py", line 841, in <module>
    main()
  File "pokecli.py", line 200, in main
    bot.tick()
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 713, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/cell_workers/transfer_pokemon.py", line 30, in work
    self._release_pokemon_worst_in_group(group, pokemon_name)
  File "/home/dibyendu/PokemonGo/PokemonGo-Bot-Dev/PokemonGo-Bot/pokemongo_bot/cell_workers/transfer_pokemon.py", line 59, in _release_pokemon_worst_in_group
    pokemon_name)
TypeError: 'NoneType' object is not iterable
```

**Comment by xiatianyu** [comment]
Getting the same error as @db-coder since the last update.

```
Traceback (most recent call last):
  File "pokecli.py", line 841, in <module>
    main()
  File "pokecli.py", line 200, in main
    bot.tick()
  File "/home/xx/Downloads/PokemonGo-Bot/pokemongo_bot/__init__.py", line 713, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/xx/Downloads/PokemonGo-Bot/pokemongo_bot/cell_workers/transfer_pokemon.py", line 30, in work
    self._release_pokemon_worst_in_group(group, pokemon_name)
  File "/home/xx/Downloads/PokemonGo-Bot/pokemongo_bot/cell_workers/transfer_pokemon.py", line 59, in _release_pokemon_worst_in_group
    pokemon_name)
TypeError: 'NoneType' object is not iterable
```

**Comment by einszA** [comment]
#5473 fixed this for me! Thanks :thumbsup:

**Comment by Faithu** [comment]
Mines counting every pokemon as VIP as well.

**Comment by davidakachaos** [comment]
As far as I could see, it isn't the config you set the causes the bot to think "all" pokemons are VIP.
I think it has to do with these lines:
```python
catch_results['fa'] = ( len(pokemon_config.get('fast_attack', [])) == 0 or unicode(pokemon.fast_attack) in map(lambda x: unicode(x), pokemon_config.get('fast_attack', [])))
        catch_results['ca'] = ( len(pokemon_config.get('charged_attack', [])) == 0 or unicode(pokemon.charged_attack) in map(lambda x: unicode(x), pokemon_config.get('charged_attack', [])))
```
I haven't set the "fast_attack" or "charged_attack" in my config:
```json
"catch": {
      "any": {"candy_threshold" : 400 ,"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "vips" : {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
```
Yes I catch all pokemon, but no it shouldn't be a VIP unless it's in my list OR is has high(ish) CP or IV.
Shouldn't this
```python
len(pokemon_config.get('fast_attack', [])) == 0
```
change to:
```python
len(pokemon_config.get('fast_attack', [])) > 0
```
Wouldn't that check IF there is a fast_attack set?

**Comment by xiatianyu** [comment]
Additional observation:
Pokémon transfer is now broken too, and it has similar syntax in the `config.json` file.
```
"release": {
      "any": {"release_below_cp": 1000, "release_below_iv": 0.9, "logic": "and"},
      "Pidgey": {"keep_best_iv": 35},
      "Weedle": {"keep_best_iv": 20},
      "Caterpie": {"keep_best_iv": 15},
      …
}
```
The first rule `"any": {"release_below_cp": 1000, "release_below_iv": 0.9, "logic": "and"}` is not taking effect. I suspect it's related to the problem in question.

**Comment by mmixx** [comment]
Yep... I confirm... transfer is broken too...

**Comment by Gobberwart** [comment]
Fixing VIP issue now

**Comment by Gobberwart** [comment]
Fixed in PR. Waiting on merge.

**Comment by Gobberwart** [comment]
There were two issues here:

1. If you didn't have a specific setting in your catch (eg. "catch_above_ncp") the bot would treat it as if you did and always catch.

2. Everything was a vip because the _is_vip function was calling the same faulty catch rules (for no apparent reason)

**Comment by clubza1** [comment]
last pull same problem all VIP

**Comment by Gobberwart** [comment]
Fixed now

**Comment by Pjumpod** [comment]
I check from latest version fef7694 still not yet fixed.
I don't have ability to check on dev branch.. sorry about this.

**Comment by avexus** [comment]
@Gobberwart is it only fixed on dev?
My mater branch still treats every one as VIP.

**Comment by Gobberwart** [comment]
Unless someone has pushed dev to master, yes.
