### ISSUE TITLE
AttributeError: 'MoveToFortWorker' object has no attribute 'position'

### ISSUE THREAD

**Issue by Koifman** [PokemonGoF/PokemonGo-Bot#566]
### Actual Behavior
AttributeError: 'MoveToFortWorker' object has no attribute 'position'

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by ritashugisha** [comment]
should have been fixed by #563

**Comment by Koifman** [comment]
Downloaded the latest version, double checked everything but still getting that error.

**Comment by ritashugisha** [comment]
does the MoveToForkWorker object actually have the position property? if not you are most likely still behind the latest commit.

**Comment by surfaace** [comment]
please check with latest DEV branch and paste git commit if issue persists

**Comment by surfaace** [comment]
no respons
